[build]
builder = "nixpacks"
buildCommand = "rm -rf /app/node_modules/.cache && rm -rf node_modules && npm cache clean --force && npm ci --omit=dev"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"] 